### ISSUE TITLE
Use callable instead of \Closure in ArrayType

### ISSUE THREAD

**Issue by tomasfejfar** [consistence/consistence#23]
It is an unnecessary because [`array_map`](http://php.net/manual/en/function.array-map.php) already uses callable. Is there a reason for using  `\Closure`?

**Comment by VasekPurchart** [comment]
I don't understand the mention of `array_map`, all the methods in `ArrayType` have consistent interface - naming, parameters and using `Closure`s.

Regarding the fact why `Closure` is used instead of `callable` is because I believe, `callable` should not be used anywhere if possible. I know that `callable` can accept `Closure`, but it can also accept a lot of other "stuff", for example strings or arrays that are then somehow evaluated. This leads to much less readable and maintainable code, so it's discouraged in [Consistence Coding Standard](https://github.com/consistence/coding-standard/blob/master/consistence-coding-standard.md#closures-and-callables) to which obviously Consistence adheres :) This is in line with Consistence trying to avoid all PHPs magic not obvious behavior.

Are you solving a situation which can not be handled by `Closure`? When we were evaluating this a few years back we did not find any legit reasons to use `callable`.

**Comment by tomasfejfar** [comment]
Sorry about the `array_map` - *"`array_map` and other array functions"* would have been easier to understand. 

I imagine `ArrayType::mapValuesByCallback($array, [MyClass::class, 'mappingMethod'])` would be a valid use. Extracting common mapping functions to class seems to be a sensible approach. Obviously it could be worked around with `ArrayType::mapValuesByCallback($array, function($item) { return MyClass::mappingMethod($item); })`, but that seems bit too self-serving. 

You're right that using string/array callables should be discouraged because it most probably breaks automatic refactoring and such. There is at least one [valid and elegant use of callable](https://3v4l.org/h9MaR) though.

**Comment by VasekPurchart** [comment]
> Obviously it could be worked around with `ArrayType::mapValuesByCallback($array, function($item) { return MyClass::mappingMethod($item); })`, but that seems bit too self-serving. 

This is exactly how we were writing things and why this exists, after dealing with many bugs caused by forgotten uses of these calls. Its also much more readable. And another benefit, which we came to appreciate especially since PHP 7 is the fact, that this encourages you to define typehints, so this would then probably look something more like this:

```php
ArrayType::mapValuesByCallback(
    $array,
    function(Item $item): string {
        return MyClass::mappingMethod($item);
    }
)
```

This further improves both readability and actually revealed a lot of bugs when using instead of foreach based approaches :)

> You're right that using string/array callables should be discouraged because it most probably breaks automatic refactoring and such. There is at least one [valid and elegant use of callable](https://3v4l.org/h9MaR) though.  

Well this is for me again relying on another PHP magic behavior :) To be honest I had to stare at the example quite a while to get it (since I haven't used invoke for a really long time), wouldn't it be much more readable [like this](https://3v4l.org/qnMtg)? Sure, it's more verbose, but especially in this case I don't think that is a bad thing. You can actually see what method is executed and how the parameters are handled. In the invoke implementation, you have to *know* the implementation and also don't see if the prescribed "contract" of the callable is actually fulfilled.

**Comment by tomasfejfar** [comment]
Explicitness is great most of the time and I'm well aware of how it works against bugs. But sometimes I'd go for elegance nevertheless. There are cases where "knowing" things is actually easier than "seeing" things. I'm still waiting for first "code amount fatigue" bug, but I'm sure they exist. I probably almost quadrupled the amount of code I write for any given feature. Most of the time it's for the best, but sometimes I'd prefer a bit more magic spaghetti. Not because it's fewer characters to write, but because it's fewer characters to read. 

Anyway, it's fine for `consistence` to be opinionated in this case. And that's pretty much why I didn't post PR straight away - I was sure there is some reason for it.
