### ISSUE TITLE
Enum::getAvailableValues() return type

### ISSUE THREAD

**Issue by simPod** [consistence/consistence#41]
PHPStan with consistence v2 now reports

> Cannot access offset mixed on iterable

When acessing eg. `EnumClass::getAvailableValues()[$name]` https://github.com/consistence/consistence/blob/master/src/Enum/Enum.php#L62

However, those values have offset as is also said in documentation

> /** @var mixed[] format: enum name (string) => cached values (const name (string) => value (mixed)) */

Thus the type hint should IMO be `array`, not `iterable`.

Or is there a better solution? I usually try to incline to suppressing PHPStan warnings as the last resort of solving something. Thanks!

**Comment by ondrejmirtes** [comment]
> Now to the issue at hand. I am not sure how PHPStan handled this before, since the interface has not changed - it was only mixed[] before

`mixed[]` in phpDoc without native typehint is an array for PHPStan, but `mixed[]` in phpDoc with `iterable` in native typehint is an iterable of integers. That means that the value cannot be safely passed for example to `count()` or `implode()`.

Do you think there are implementations that return something else than array? I think it would be too impractical.

**Comment by simPod** [comment]
> The fact that it returned the special format it did was only an implementation detail of the default implementation and returning the values was just "why not if they are there"

I have analysed my `getAvailableValues()` usages and 90 % of cases I work with keys or do other array operations like `array_flip()` or `array_keys()`. Having keys there is very useful, at least for my usecase. So it looks like I'll have to go with overriding then.

**Comment by VasekPurchart** [comment]
> Do you think there are implementations that return something else than array? I think it would be too impractical.

Yeah, sure, it can be `yield` (even [Symfony uses it in 4.x](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php#L33 although not with an return type hint unfortunately) or any Iterator such as a collection etc.

@ondrejmirtes Is this behavior special for `mixed`, or is it true for any type? Because I think it should work like that anywhere.

> That means that the value cannot be safely passed for example to count() or implode().

Yeah, that is exactly the point, in this case it should not be safe to pass `Enum::getAvailableValues()` to these, because you don't know that there will be any keys, the **interface** does not require them. The implementation can be overridden. So that is why I recommended overriding the type, if @simPod is really sure that all his **implementations** return them, then the type can be changed.

Anyway as I already wrote above, the issue is caused by the interface vs implementation and what should be noted there. If I had an interface (which does not make sense in this case) then I would have `iterable` in interface and `array` in implementation (to be as specific as possible in return type). But because of the need to use inheritance the implementation becomes the interface and if I put `array` there it would force everyone to use `array` for no reason at all.

So again, this is about relying on interface vs implementation.

---

My more general thoughts about this:

> Do you think there are implementations that return something else than array? I think it would be too impractical.

I think we (as in PHP) need a way how to document keys (at least, generics and proper Collections, Sets etc. would be better of course).

Until then if you consider `string[]` as an array, you really don't know anything about the keys anyway (well you know `int|string`, but you know...  :) ). We help ourselves with the distinction being that you have to document the keys, if you want to rely on them. But if we write only `string[]` we consider it being an `iterable`, because you don't know if it is a Collection, where you might need to call `->count()` instead or it is really not possible (or practical) at all. If there was something like `array<string, string>` everything would be clear of course.

But these cases are really rare for us, because if we want to rely on the keys, we usually create some classes describing them more granularly.

**Comment by VasekPurchart** [comment]
> I have analysed my getAvailableValues() usages and 90 % of cases I work with keys or do other array operations like array_flip() or array_keys(). Having keys there is very useful, at least for my usecase. So it looks like I'll have to go with overriding then.

If you use things like `array_keys` I really think these should probably be methods defined on the `Enum` (like `::getConstantNames()`), but again, it already relies on the implementation, so you would probably be better of with an extended class for your use cases anyway.

**Comment by ondrejmirtes** [comment]
> Is this behavior special for mixed, or is it true for any type? Because I think it should work like that anywhere.

It works the same way. `int[]` with `iterable` becomes `iterable<int>`.

So if one needs an array there, they should use their own abstract class for their own project enums, right? Since `array|Traversable` (iterable) -> `array` is covariant, then I think it's fine for the return typehint. Unfortunately right now it's not possible to persuade PHPStan that a child class returns array (the `iterable` has to stay in the return typehint because of PHP limitation): https://phpstan.org/r/c13a260a-1672-432d-a614-aaf53142509b

**Comment by janlanger** [comment]
@ondrejmirtes `iterable` actually allows variance and you can narrow `iterable` to `array` in child return type. http://php.net/manual/en/language.types.iterable.php
https://phpstan.org/r/9bdbda29-a55e-4670-895b-c2edf15bb42f

So custom Enum parent could be actually work, right?

**Comment by VasekPurchart** [comment]
> It works the same way. `int[]` with iterable becomes `iterable<int>`.

But `int[]` without a return type hint becomes `array<int>`? I think this is probably fine (practical) for return types (covariance), but I don't think this is good for params (contravariance), because then you might call the `count` on something which is really just an `iterable`. But again, I think this is caused mainly by lack of means how to write types properly :(

@janlanger is right I have already used the same thing somewhere else in Consistence 2.0, you can (at least on 7.2 override, wasn't it changed?).

**Comment by VasekPurchart** [comment]
Also I plan using `iterable` as much as possible (and `array` in interfaces as little as possible), because it leads to much more reusable code (even in non-library -> project code) + we have found out, that we actually mostly use foreach anyway or some of the array fucntions (but via Consistence), but I plan to have a IterableType with the same functionality in a comming release (was wainting at first for PHP versions and then did not have time :) ).

**Comment by ondrejmirtes** [comment]
@janlanger Nice, I didn't know that!

**Comment by simPod** [comment]
I guess this can be closed. Thanks for comments!
